### ISSUE TITLE
Postfix for debug libraries

### ISSUE THREAD

**Issue by haferburg** [devernay/cminpack#17]
Hi Frédéric

Issue 1: Would you mind adding a debug postfix to the debug builds?

	if (BUILD_SHARED_LIBS)
	  message (STATUS "Building shared libraries.")
	  set(CMAKE_DEBUG_POSTFIX -gd)
	else ()
	  message (STATUS "Building static libraries.")
	  set(CMAKE_RELEASE_POSTFIX _s)
	  set(CMAKE_RELWITHDEBINFO_POSTFIX _s)
	  set(CMAKE_DEBUG_POSTFIX _s-gd)
	  set(CMAKE_MINSIZEREL_POSTFIX _s)
	  if(WIN32)
		add_definitions(-DCMINPACK_NO_DLL)
	  endif(WIN32)
	endif ()

Issue 2: There is a warning in CMake because of this condition.

	if (OS_LINUX OR ${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
		option (USE_FPIC "Use the -fPIC compiler flag." ON)
	else (OS_LINUX)
		option (USE_FPIC "Use the -fPIC compiler flag." OFF)
	endif (OS_LINUX)

Warning:

    CMake Warning (dev) in CMakeLists.txt:
      A logical block opening on the line

        C:/src/cminpack-1.3.6/CMakeLists.txt:23 (if)

      closes on the line

        C:/src/cminpack-1.3.6/CMakeLists.txt:27 (endif)

      with mis-matching arguments.
    This warning is for project developers.  Use -Wno-dev to suppress it.

I would change it to:

	if (OS_LINUX OR ${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
		option (USE_FPIC "Use the -fPIC compiler flag." ON)
	else ()
		option (USE_FPIC "Use the -fPIC compiler flag." OFF)
	endif ()

Cheers
Andreas

**Comment by devernay** [comment]
Issue1: Are you building on visual studio? why `-gd`and not `_d`? Is there some standard for the debug postfix, and is it the same across all archs? 

Issue2: OK

**Comment by haferburg** [comment]
Yes, Visual Studio. Normally I use "d" as the suffix. I don't know if there is a standard, but I doubt it.

I believe the preferred way would be to have CMake install a cminpack-config.cmake file that contains this information. The exact file name is not that important as long as CMake is able to find it programmatically for library users.

**Comment by devernay** [comment]
fixed by b5500b64eed3734959dcf7b098f33e872f12f52a
(use _d instead of -gd, and do not override value provided on the cmake command-line)
