### ISSUE TITLE
1.3.7 release

### ISSUE THREAD

**Issue by tadeu** [devernay/cminpack#25]
Hi @devernay! First, thanks for maintaining this project, it's awesome to have an actually maintained "alternative" to the very old Fortran MINPACK!
I'd like to know if there are plans for a new 1.3.7 release (or if it could be released soon), because I'd like to create packages for `cminpack` on conda-forge. Thanks!

**Comment by tadeu** [comment]
But perhaps let's wait, I'll start a work-in-progress PR there in conda-forge and let you know

**Comment by devernay** [comment]
is there anything in 1.3.6 that doesn't work for you? You should really consider using it, since it's very stable

**Comment by tadeu** [comment]
I'm trying to build on 1.3.6 there right now, let's see: https://github.com/conda-forge/staged-recipes/pull/7766

**Comment by devernay** [comment]
what was wrong with tlmdif?

**Comment by devernay** [comment]
(I will do the 1.3.7 release, unless there is something wrong with tlmdif)

**Comment by tadeu** [comment]
> what was wrong with tlmdif?

Ahh, I don't remember it exactly, but some results were slightly different from the expected values in the test when using OpenBLAS, e.g., 0.002869942 instead of 0.002869941. But I think it was related more to the choice of BLAS library than to the 1.3.6 release.

**Comment by xantares** [comment]
any news on this ?
for me, it's the fact that cminpack does not correctly link to cblas that is annoying (#21) with the 1.3.6
regards

**Comment by devernay** [comment]
done!

**Comment by xantares** [comment]
thanks!
