### ISSUE TITLE
Functions missing in windows

### ISSUE THREAD

**Issue by cjzubiaga** [devernay/cminpack#39]
I'm compiling a fortran package in linux and windows.
It perfectly link with minpack in linux, but the next functions are missing in windows:
 `qrfac_' `qform_' `dogleg_' `r1updt_' `r1mpyq_' `r1mpyq_'
I'm using the package stored in conda-forge

**Comment by tadeu** [comment]
The symbols seem to be there in `cminpack_s.lib`. How are you linking to it?

**Comment by cjzubiaga** [comment]
In the conda package there is a `cminpack.lib` but not a `cminpack_s.lib`.
The linker I'm using is `ld` of `mingw32`.
The linker is called by `disttulis` of `numpy`
Everything is obtained with anaconda


I get the next errors:
```
undefined reference to `qrfac_'
undefined reference to `qform_'
undefined reference to `dogleg_'
undefined reference to `r1updt_'
undefined reference to `r1mpyq_'
undefined reference to `r1mpyq_'
```
If I do not link with `cminpack` I also have the same errors and `dpmpar_' `enorm_' `enorm_' `enorm_' `enorm_' `enorm_'  `enorm_' as well not found

**Comment by tadeu** [comment]
Indeed, the symbols are not in the lib in version 1.3.6 (before I was looking into 1.3.5, not from conda-forge).

Are these functions supposed to be publicly exported in `cminpack`? The seem to lack `CMINPACK_EXPORT`, also they are not declared in public headers, and are not tested.

**Comment by devernay** [comment]
Those are internal functions in MINPACK, and are not supposed to be exported.
See here: https://github.com/devernay/cminpack/blob/master/minpack.h#L275
and here: https://github.com/devernay/cminpack/blob/master/cminpack.h#L343

If an external package uses these functons directly, it should probably include the source code for these as well.
My guess is that the package you are trying to compile includes the source for hybrj or hybrd, but forgot to include dependencies.

I don't see much point in exposing/exporting these functions.

**Comment by devernay** [comment]
note that dpmpar_ and enorm_ are explicitely exported here: https://github.com/devernay/cminpack/blob/d1f5f5a273862ca1bbcf58394e4ac060d9e22c76/minpack.h#L244

**Comment by devernay** [comment]
but of course you would have to include "minpack.h" from this package
