### ISSUE TITLE
Malformed version in generated pkgconfig file

### ISSUE THREAD

**Issue by StefanBruens** [devernay/cminpack#55]
The `CMINPACK_VERSION` variable contains a semicolon separated list of strings:
https://github.com/devernay/cminpack/blob/262edbdc674431e08d9441790cf5cc6d040d701d/CMakeLists.txt#L17

i.e. `1.3.9;STRING;CMinpack\ version`. See https://cmake.org/cmake/help/latest/command/set.html#set :
> Multiple arguments will be joined as a [semicolon-separated list](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#cmake-language-lists) to form the actual variable value to be set.

After https://github.com/devernay/cminpack/blob/262edbdc674431e08d9441790cf5cc6d040d701d/CMakeLists.txt#L174

the pkgconfig file contains the following Version field:
```
Version: 1.3.8;STRING;CMinpack version
```

**Comment by devernay** [comment]
Thanks!
can you please contribute a fix (by way of PR)?
