### ISSUE TITLE
When will the version 1.3.9 be released ?

### ISSUE THREAD

**Issue by hxhc** [devernay/cminpack#60]
Hi @devernay , I found that in the version 1.3.8, cmake fails to find BLAS, and says `cannot find MKL tool`.

while in the master branch, `find_package(CBLAS)` has been replaced by `find_package (BLAS)`. I tried the master branch version and it succeeded to find BLAS (both MKL and OpenBLAS). Since the previous 1.3.8 version was released in 2021, it might be suitable to release a new version containing some modern "features", at least for the BLAS issue. Anyway, thank you for the great library!

**Comment by imciner2** [comment]
A new release would be appreciated. I am working on moving this into the modern Julia binary system (Yggdrasil), and so we'd appreciate being able to use a recent release and not need to backport commits as patches on top of 1.3.8.

**Comment by devernay** [comment]
done!
