### ISSUE TITLE
Iteration numbers in cminpack

### ISSUE THREAD

**Issue by LittleDogXi** [devernay/cminpack#67]
The parameter "nfev" is the number of fcn calls. But how can I know the iteration numbers using hybrd function?

**Comment by luau-project** [comment]
According to the user guide for minpack, which can be found at
* Moré, Jorge J., Burton S. Garbow, and Kenneth E. Hillstrom. User guide for MINPACK-1.[In FORTRAN]. No. ANL-80-74. Argonne National Lab.(ANL), Argonne, IL (United States), 1980. DOI: [10.2172/6997568](https://doi.org/10.2172/6997568)

when you supply the param ```nprint``` a positive integer, it enables controlled printing of iterates.

**Comment by LittleDogXi** [comment]
I set param `nprint` a postive integer like +1, but I cannot see any printing of iterates in the console. Is the information printed somewhere else?

**Comment by luau-project** [comment]
I never experimented this ```nprint``` param myself, but judging by the docs linked above, I guess you would be called ```nprint``` times in the callback or something in that direction.

**Comment by LittleDogXi** [comment]
I will try it soon later.

**Comment by LittleDogXi** [comment]
After a few tries, I have figured it out. Set `nprint` a positive integer, like 1, and add `if(*flag==0){std::cout<<"$";}` in the `fcn` function, you could print serval $ characters, which has the same number of iteration times.

**Comment by luau-project** [comment]
I'm glad that you solved the puzzle.
