### ISSUE TITLE
The Download Link is broken

### ISSUE THREAD

**Issue by cxlove** [devernay/cminpack#7]
https://homebrew.bintray.com/bottles/cminpack-1.3.4.yosemite.bottle.tar.gz

http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz

The above links are broken, so it can't use brew to install in MacOs
Could you fix it ?

**Comment by devernay** [comment]
the second one works for me

**Comment by zepinglee** [comment]
The second link is blocked in China.

**Comment by devernay** [comment]
if it is blocked, get the latest source distributions from github:
https://github.com/devernay/cminpack/releases
--
Frédéric Devernay, Research Scientist, INRIA
frederic.devernay@inria.fr

**Comment by LuZhouheng** [comment]
@zepinglee This article must be helpful for you. 

https://www.logcg.com/zh-tw/archives/1617.html

link's blocking due to proxy in terminal. I success get the source by following this tutorial with shadow-socks.

Hope it's helpful for you.
